### ISSUE TITLE
Externalize session data to make the app more stateless/production-ready

### ISSUE THREAD

**Issue by brittag** [18F/cf-ex-wordpress#10]
Similar to [this comment about `cf-ex-drupal`](https://github.com/18F/cf-ex-drupal/issues/5), we should address this limitation (from the README) with instructions for using the RDS or Redis services, instead of leaving it as a caution:

> This is not an issue with Wordpress specifically, but PHP stores session information to the local disk. As mentioned previously, the local disk for an application on CloudFoundry is ephemeral, so it is possible for you to lose session and session data. If you need reliable session storage, look at storing session data in an SQL database or with a NoSQL service.

**Comment by mogul** [comment]
@LinuxBozo in case he has thoughts.

**Comment by mogul** [comment]
It looks like there's [an extension in the PHP buildpack that will make use of a Redis service for session storage](https://github.com/cloudfoundry/php-buildpack/blob/master/extensions/sessions/extension.py) if one's available...! I just don't know what you have to do in order to have it recognize and use your service. Will investigate further!

**Comment by mogul** [comment]
As far as I can tell, all you have to do is [create a Redis service instance called `redis-sessions`](https://github.com/cloudfoundry/php-buildpack/blob/master/extensions/sessions/extension.py#L39) and the buildpack will automatically configure PHP to use it for session storage!

cc @gboone

**Comment by mogul** [comment]
Surprise, [it's documented!](http://docs.cloudfoundry.org/buildpacks/php/gsg-php-sessions.html)

**Comment by mogul** [comment]
Turns out we didn't need to do anything... Wordpress stores sessions client-side and that comment in the readme was a spurious holdover from someone copying the cf-ex-drupal example. 🤦‍♂️
