### ISSUE TITLE
Plugin info needs to be updated

### ISSUE THREAD

**Issue by brittag** [18F/cf-ex-wordpress#9]
I just tried deploying this, and it still mostly works except that step 9 no longer makes sense:

> * Click on AWS in the left navigation menu
> * Click on S3 and CloudFront in navigation menu
> * Turn on `Copy Files to S3` and `Rewrite File URLs`
> * Scroll to the bottom, and click Save Changes

That's not what the interface looks like anymore. This is probably at least partially because the plugin versions in `setup.json` are very old...

Guessing we need to update the plugin versions and rework the instructions for this a bit.

**Comment by mogul** [comment]
@LinuxBozo do you want to weigh in here? Is this white-noise or below?

**Comment by LinuxBozo** [comment]
@mogul It should be. This hasn't been touched in a while, so examples are all going to be out of date.

**Comment by gboone** [comment]
I think for this we need only to increment the versions on the aws plugins. Once I had the right version those options came back. I could clarify in #12 that the AWS menu is in the bottom of the left hand nav menu.

**Comment by brittag** [comment]
[This support ticket had issues with the S3 plugin as well](https://cloud-gov.zendesk.com/agent/tickets/661)

**Comment by mogul** [comment]
This should be resolved by #12

**Comment by gboone** [comment]
Yeah, those directions aren't in the README anymore and the we're using a different plugin.
